#!/usr/bin/env bash
# ============================================================================
# GroktoCrawl all-in-one entrypoint
#
# Responsibilities:
#   1. Resolve EMBED_* toggles (auto mode: start an embedded component only
#      when no external URL has been configured for it).
#   2. Generate /etc/searxng/settings.yml (private instance, JSON API on,
#      multilingual relevance defaults, optional engine disable list).
#   3. Emit supervisor program files for every component that should run.
#   4. exec supervisord -n  (PID1 handles signals + zombie reaping).
#
# Every upstream env var passes through unchanged — extra services pick their
# own settings up from the environment (docker-compose env_file: .env).
# ============================================================================
set -euo pipefail

LOGDIR=/var/log/groktocrawl
DATA_ROOT="${GROKTOCRAWL_DATA:-/data}"
CONF_DIR=/etc/supervisor/conf.d

mkdir -p "$DATA_ROOT/valkey" "$DATA_ROOT/qdrant" "$DATA_ROOT/huggingface" \
         "$DATA_ROOT/cloakbrowser" "$DATA_ROOT/config" \
         "$LOGDIR" "$CONF_DIR"

log() { printf '[groktocrawl-aio] %s\n' "$*" >&2; }

# ── Helper: authority of a host:port part ──────────────────────────────────
url_host() {
    # http://127.0.0.1:8888 -> 127.0.0.1 ; empty input -> empty output
    python3 - "$1" <<'PYEOF'
import sys, urllib.parse as u
try:
    print(u.urlsplit(sys.argv[1]).hostname or "")
except Exception:
    print("")
PYEOF
}

is_local_url() {
    local h; h="$(url_host "${1:-}")"
    case "$h" in
        ""|127.0.0.1|localhost|::1|0.0.0.0) return 0 ;;
        *) return 1 ;;
    esac
}

# ── Resolve embedded toggles ───────────────────────────────────────────────
VALKEY_HOST="${VALKEY_HOST:-127.0.0.1}"
VALKEY_PORT="${VALKEY_PORT:-6379}"
VALKEY_DB="${VALKEY_DB:-0}"
export VALKEY_URL="${VALKEY_URL:-redis://${VALKEY_HOST}:${VALKEY_PORT}/${VALKEY_DB}}"

export SCRAPER_URL="${SCRAPER_URL:-http://127.0.0.1:8001}"
export BROWSER_SVC_URL="${BROWSER_SVC_URL:-http://127.0.0.1:8012}"
export SEMANTIC_URL="${SEMANTIC_URL:-http://127.0.0.1:8003}"
export QDRANT_URL="${QDRANT_URL:-http://127.0.0.1:6333}"
export SEARXNG_URL="${SEARXNG_URL:-http://127.0.0.1:8888}"
export LLM_BASE_URL="${LLM_BASE_URL:-http://127.0.0.1:8011/v1}"
export AGENT_BASE_URL="${AGENT_BASE_URL:-http://127.0.0.1:8080}"
export GROKTOCRAWL_URL="${GROKTOCRAWL_URL:-http://127.0.0.1:8080}"

embed_enabled() {
    # $1 toggle name   $2 auto-condition command ("true" = embed)
    local toggle="$1"
    case "${toggle}" in
        false|False|no|No|0) return 1 ;;
        true|True|yes|Yes|1) return 0 ;;
        *)                                   # auto
            [ "$2" = "true" ]
            ;;
    esac
}

if embed_enabled "${EMBED_VALKEY:-auto}" "$(is_local_url "${VALKEY_URL}" && echo true || echo false)"; then
    START_VALKEY=true
else
    START_VALKEY=false
fi
if embed_enabled "${EMBED_QDRANT:-auto}" "$(is_local_url "${QDRANT_URL}" && echo true || echo false)"; then
    START_QDRANT=true
else
    START_QDRANT=false
fi
if embed_enabled "${EMBED_SEARXNG:-auto}" "$(is_local_url "${SEARXNG_URL}" && echo true || echo false)"; then
    START_SEARXNG=true
else
    START_SEARXNG=false
fi
# LLM fixture: only meaningful for zero-config demos. Start when no external
# OpenAI-compatible endpoint was given and it is not explicitly disabled.
START_LLM_FIXTURE=false
if embed_enabled "${EMBED_LLM_FIXTURE:-auto}" "$(is_local_url "${LLM_BASE_URL}" && echo true || echo false)"; then
    if [ -z "${LLM_API_KEY:-}" ]; then
        START_LLM_FIXTURE=true
    fi
fi

START_MONITORS=false
case "${MONITOR_SCHEDULER_ENABLED:-true}" in
    true|True|yes|Yes|1) START_MONITORS=true ;;
esac

log "embedded components: valkey=${START_VALKEY} qdrant=${START_QDRANT} searxng=${START_SEARXNG} llm-fixture=${START_LLM_FIXTURE} monitor-loop=${START_MONITORS}"

# ── SearXNG settings generation ────────────────────────────────────────────
S_WORKERS="${SEARXNG_WORKERS:-2}"
S_THREADS="${SEARXNG_THREADS:-12}"
if [ "${START_SEARXNG}" = "true" ]; then
    mkdir -p /etc/searxng
    SECRET_FILE="$DATA_ROOT/config/searxng_secret_key"
    if [ ! -s "$SECRET_FILE" ]; then
        python3 -c 'import secrets,sys; open(sys.argv[1],"w").write(secrets.token_hex(32))' "$SECRET_FILE"
        chmod 600 "$SECRET_FILE"
    fi
    S_KEY=$(cat "$SECRET_FILE")

    python3 - "$S_KEY" <<'PYEOF'
import os
import sys

key = sys.argv[1]
disabled = [e.strip() for e in os.getenv("SEARXNG_DISABLED_ENGINES", "").split(",") if e.strip()]

if disabled:
    lines = [
        "# AUTO-GENERATED by groktocrawl-aio-entrypoint — do not edit here.",
        "# Override entirely by bind-mounting your own file over /etc/searxng/settings.yml",
        "",
        "use_default_settings:",
        "  engines:",
        "    remove:",
    ]
    lines.extend(f"      - {e}" for e in disabled)
else:
    lines = [
        "# AUTO-GENERATED by groktocrawl-aio-entrypoint — do not edit here.",
        "# Override entirely by bind-mounting your own file over /etc/searxng/settings.yml",
        "",
        "use_default_settings: true",
    ]
lines += [
    "",
    "server:",
    f"  secret_key: '{key}'",
    "  limiter: false          # private single-user instance: no bot-detection throttle",
    "  image_proxy: true",
    "  public_instance: false",
    "",
    "search:",
    "  safe_search: 0",
    "  autocomplete: 'google'",
    "  default_lang: 'auto'    # per-query language autodetect → high CJK relevance",
    "  formats: [html, json, csv, rss]",
    "",
    "ui:",
    "  static_use_hash: true",
]

open("/etc/searxng/settings.yml", "w").write("\n".join(lines) + "\n")
PYEOF
    log "generated /etc/searxng/settings.yml"
fi

# ── Supervisor program emission helpers ────────────────────────────────────
emit_program() { # name priority stdout_logfile command...
    local name="$1" prio="$2" logfile="$3"; shift 3
    {
        echo "[program:${name}]"
        echo "command=${*}"
        echo "directory=/app"
        echo "priority=${prio}"
        echo "autostart=true"
        echo "autorestart=unexpected"
        echo "exitcodes=0"
        echo "startsecs=5"
        echo "startretries=15"
        echo "stopsignal=TERM"
        echo "stopasgroup=true"
        echo "killasgroup=true"
        echo "stopwaitsecs=25"
        echo "redirect_stderr=true"
        echo "stdout_logfile=${logfile}"
        echo "stdout_logfile_maxbytes=20MB"
        echo "stdout_logfile_backups=3"
        echo "environment=PYTHONPATH=\"/app\",PYTHONUNBUFFERED=\"1\""
    } > "${CONF_DIR}/${name}.conf"
}

# ── Embedded infrastructure ────────────────────────────────────────────────
if [ "${START_VALKEY}" = "true" ]; then
    emit_program valkey 10 "/var/log/groktocrawl/valkey.log" \
        redis-server --bind 127.0.0.1 --port "${VALKEY_PORT}" \
        --dir "$DATA_ROOT/valkey" --appendonly yes --appendfsync everysec --save ""
fi

if [ "${START_QDRANT}" = "true" ]; then
    {
        echo "[program:qdrant]"
        echo "command=/opt/qdrant/qdrant"
        echo "directory=${DATA_ROOT}/qdrant"
        echo "priority=20"
        echo "autostart=true"
        echo "autorestart=unexpected"
        echo "exitcodes=0"
        echo "startsecs=5"
        echo "startretries=15"
        echo "stopsignal=TERM"
        echo "stopasgroup=true"
        echo "killasgroup=true"
        echo "stopwaitsecs=25"
        echo "redirect_stderr=true"
        echo "stdout_logfile=/var/log/groktocrawl/qdrant.log"
        echo "stdout_logfile_maxbytes=20MB"
        echo "stdout_logfile_backups=3"
        echo "environment=QDRANT__SERVICE__HOST=\"127.0.0.1\",QDRANT__SERVICE__HTTP_PORT=\"6333\",QDRANT__STORAGE__STORAGE_PATH=\"${DATA_ROOT}/qdrant/storage\",QDRANT__STORAGE__SNAPSHOTS_PATH=\"${DATA_ROOT}/qdrant/snapshots\""
    } > "${CONF_DIR}/qdrant.conf"
fi

if [ "${START_SEARXNG}" = "true" ]; then
    {
        echo "[program:searxng]"
        echo "command=gunicorn --workers ${S_WORKERS} --threads ${S_THREADS} --worker-class gthread --timeout 120 --graceful-timeout 30 --bind 127.0.0.1:8888 searx.webapp:app"
        echo "directory=/app"
        echo "priority=20"
        echo "autostart=true"
        echo "autorestart=unexpected"
        echo "exitcodes=0"
        echo "startsecs=5"
        echo "startretries=15"
        echo "stopsignal=TERM"
        echo "stopasgroup=true"
        echo "killasgroup=true"
        echo "stopwaitsecs=25"
        echo "redirect_stderr=true"
        echo "stdout_logfile=/var/log/groktocrawl/searxng.log"
        echo "stdout_logfile_maxbytes=20MB"
        echo "stdout_logfile_backups=3"
        echo "environment=PYTHONPATH=\"/app\",SEARXNG_SETTINGS_PATH=\"/etc/searxng/settings.yml\",SEARX_SETTINGS_PATH=\"/etc/searxng/settings.yml\""
    } > "${CONF_DIR}/searxng.conf"
fi

# ── Core GroktoCrawl services ──────────────────────────────────────────────
emit_program parse-svc 30 "/var/log/groktocrawl/parse-svc.log" \
    python -m uvicorn parse_svc.app:app --host 0.0.0.0 --port 8013

emit_program browser-svc 30 "/var/log/groktocrawl/browser-svc.log" \
    python -m uvicorn browser_svc.app:app --host 0.0.0.0 --port 8012

# scraper-entrypoint tries a best-effort CloakBrowser binary download into the
# mounted cache first (falls back to stock Chromium), then serves uvicorn.
{
    echo "[program:scraper-svc]"
    echo "command=/bin/bash -c '/usr/local/bin/scraper-entrypoint'"
    echo "directory=/app"
    echo "priority=30"
    echo "autostart=true"
    echo "autorestart=unexpected"
    echo "exitcodes=0"
    echo "startsecs=5"
    echo "startretries=15"
    echo "stopsignal=TERM"
    echo "stopasgroup=true"
    echo "killasgroup=true"
    echo "stopwaitsecs=25"
    echo "redirect_stderr=true"
    echo "stdout_logfile=/var/log/groktocrawl/scraper-svc.log"
    echo "stdout_logfile_maxbytes=20MB"
    echo "stdout_logfile_backups=3"
    echo "environment=PYTHONPATH=\"/app\",PYTHONUNBUFFERED=\"1\",HOME=\"/root\""
} > "${CONF_DIR}/scraper-svc.conf"

emit_program semantic-svc 40 "/var/log/groktocrawl/semantic-svc.log" \
    python -m uvicorn app:app --host 0.0.0.0 --port 8003

emit_program agent-svc 50 "/var/log/groktocrawl/agent-svc.log" \
    python -m uvicorn agent.app:app --host 0.0.0.0 --port 8080

emit_program portal-svc 60 "/var/log/groktocrawl/portal-svc.log" \
    python -m uvicorn portal.app:app --host 0.0.0.0 --port 8081

{
    echo "[program:mcp-svc]"
    echo "command=python mcp_server.py"
    echo "directory=/app/mcp_app"
    echo "priority=60"
    echo "autostart=true"
    echo "autorestart=unexpected"
    echo "exitcodes=0"
    echo "startsecs=5"
    echo "startretries=15"
    echo "stopsignal=TERM"
    echo "stopasgroup=true"
    echo "killasgroup=true"
    echo "stopwaitsecs=35"
    echo "redirect_stderr=true"
    echo "stdout_logfile=/var/log/groktocrawl/mcp-svc.log"
    echo "stdout_logfile_maxbytes=20MB"
    echo "stdout_logfile_backups=3"
    echo "environment=PYTHONPATH=\"/app:/app/mcp_app\""
} > "${CONF_DIR}/mcp-svc.conf"

if [ "${START_LLM_FIXTURE}" = "true" ]; then
    emit_program llm-fixture 35 "/var/log/groktocrawl/llm-fixture.log" \
        python -m uvicorn llm_svc.app:app --host 127.0.0.1 --port 8011
fi

# Replaces the upstream `ofelia` sidecar: run monitor checks in-process.
if [ "${START_MONITORS}" = "true" ]; then
    emit_program monitor-loop 70 "/var/log/groktocrawl/monitor-loop.log" \
        /bin/bash -c "sleep 300; while :; do python3 -m agent.monitor check_all; sleep \"\${MONITOR_INTERVAL_SECONDS:-600}\"; done"
fi

log "supervisor programs generated:"
ls -1 "${CONF_DIR}" >&2 || true

exec supervisord -n -c /etc/supervisor/supervisord.conf
